DROP TABLE IF EXISTS "Address", "Person", "Product", "Order";

CREATE TABLE "Address"(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    city TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "Person"(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    family_name TEXT NOT NULL,
    given_name TEXT NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    perm_address_id INT,
    temp_address_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_Person_perm_address FOREIGN KEY (perm_address_id) REFERENCES "Address"(id),
    CONSTRAINT fk_Person_temp_address FOREIGN KEY (temp_address_id) REFERENCES "Address"(id)
);

INSERT INTO "Person" (birth_date, family_name, given_name)
VALUES
    ('1970-01-01', 'Aberdeen', 'Abel'),
    ('1980-02-02', 'Budapest', 'Benjamin'),
    ('1990-03-03', 'Johannesburg', 'John')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE "Product"(
    id INT GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO "Product" (name)
VALUES
    ('Alien Alloys'),
    ('Stun Rod'),
    ('Grenade'),
    ('Smoke Grenade'),
    ('Proximity Grenade'),
    ('Alien Grenade'),
    ('High Explosive'),
    ('Electro-flare'),
    ('Motion Scanner'),
    ('Medi-Kit'),
    ('Psi-Amp'),
    ('Mind Probe'),
    ('Elerium')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE "Order"(
    id INT GENERATED ALWAYS AS IDENTITY,
    product_id INT NOT NULL,
    quantity INT DEFAULT 1 NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_Order_product FOREIGN KEY (product_id) REFERENCES "Product"(id)
);
